# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  - VERSION_PKG=github.com/sunny0826/kust-check/version
#  - GO_FLAGS=-ldflags="-X ${VERSION_PKG}.Ver=$(BLADE_VERSION) -X '${VERSION_PKG}.Env=`uname -mv`' -X '${VERSION_PKG}.BuildTime=`date`'"
#  ldflags: -s -X github.com/sunny0826/kust-check/cmd.Ver={{.Version}} -X github.com/sunny0826/kust-check/cmd.GitCommit={{.Commit}} -X github.com/sunny0826/kust-check/cmd.BuildTime={{.Date}}
  ldflags: -s -X ${VERSION_PKG}.Ver={{.Version}} -X ${VERSION_PKG}.GitCommit={{.Commit} -X ${VERSION_PKG}.BuildTime={{.Date}}
  goos:
    - linux
    - darwin
    - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-rc"
changelog:
  sort: asc
release:
  github:
    owner: sunny0826
    name: kust-check

  name_template: '{{.ProjectName}}-v{{.Version}}'

