os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - tree
  homebrew:
    packages:
      - tree
    update: true

# Only clone the most recent commit.
git:
  depth: 1

language: go

env:
  - GO111MODULE=on

go:
  - "1.13"

sudo: required

install:
  - go install

script:
  - echo "script"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: true